#端口和初始路径配置
#server:
#  port: 8112
#  servlet:
#    context-path: /auth

#项目名称
spring:
  application:
    name: cloud-auth
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud_demo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456789
    driver-class-name: com.mysql.jdbc.Driver
  #redis
  redis:
    host: redis-host
    port: 6379
  #mongodb
  #data:
    #mongodb:
      #database: k12-mall
      #grid-fs-database: k12-mall
      #uri: mongodb://db-host:27017/k12-mall

#日志配置
logging:
  level:
   root: info

#eureka配置
#eureka:
#    client:
#      service-url:
#          defaultZone: http://root:root@eureka-host:1111/eureka/
#           defaultZone: http://eureka-host:1111/eureka/
#logging:
#  path: /logs
#  file: springbootdemo.log
#  level:
#    root: debug
#  pattern:
#    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
#    file: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"

#jwt生成密钥密码
#test123

##########################feign-hystrix开启##########################
#ribbon:
##建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
#  ReadTimeout: 1200000
##建立连接后从服务器读取到可用资源所用的时间。
#  ConnectTimeout: 1200000
#  MaxTotalHttpConnections: 1000
#  MaxHttpConnectionsPerHost: 1000
#
#hystrix:
#    command:
#        default:
#            execution:
#                isolation:
#                    thread:
#                        timeoutInMilliseconds: 600000 #毫秒单位
#
#feign:
#    hystrix:
#      enabled: true
##########################feign-hystrix开启##########################