#设置tomcat服务端口号
server:
  port: 1111
#设置服务名称
spring:
  application:
    name: eureka-service
  security:
    user:
      name: root
      password: root

#日志配置
$log:
  level:
  default: info


#eureka配置
eureka:
  instance:
    hostname: localhost
  client:
    #避免eureka向自己进行注册
    register-with-eureka: false
    #避免eureka查找服务列表
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka