#端口和初始路径配置
server:
  port: 1112
#  servlet:
#    context-path: /config

#eureka配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
      service-url:
           defaultZone: http://root:root@eureka-host:1111/eureka/
#           defaultZone: http://eureka-host:1111/eureka/

#日志配置
$log:
  level:
  default: info

spring:
  application:
    name: cloud-config
#  security:
#    user:
#      name: root
#      password: root
# 从git获取配置文件
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wglg550/mycloud.git #配置git仓库地址
          #指定搜索路径，config-server会自动搜索根目录和指定目录（逗号分隔）下的文件
          search-paths: cloud-config/cloud-config-core,cloud-config/cloud-config-module/{application}
          profile: prod
          label: master
#          username: username #访问git仓库的用户名
#          password: password #访问git仓库的用户密码