#端口和初始路径配置
server:
  port: 8114
#  servlet:
#    context-path: /config

#eureka配置
eureka:
    client:
      service-url:
          defaultZone: http://root:root@eureka-host:1111/eureka/
#           defaultZone: http://eureka-host:1111/eureka/

#日志配置
$log:
  level:
  default: info

spring:
  application:
    name: cloud-config
# 从git获取配置文件
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wglg550/mycloud #配置git仓库地址
          #指定搜索路径，config-server会自动搜索根目录和指定目录（逗号分隔）下的文件
#          search-paths: learn-cloud-config/cloud-config-repo
          search-paths: learn-cloud-config/cloud-config-core,learn-cloud-config/cloud-config-single/{application}
#          username: username #访问git仓库的用户名
#          password: password #访问git仓库的用户密码
